tap "homebrew/cask"
cask_args appdir: "~/Applications", require_sha: true

brew "adr-tools"
brew "imagemagick"
brew "node@14"
brew "tmux"
brew "telnet"
brew "nvm"

brew "tree"
brew "watch"

tap "aws/tap"
brew "awscli"

cask "microsoft-edge"
cask "squirrel"

